//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImageConverter {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ImageConverter.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konvertierung der Datei war erfolgeich: {0}.
        /// </summary>
        internal static string Program_HandleFile_Conversion_For_File_X_Was_Successful {
            get {
                return ResourceManager.GetString("Program_HandleFile_Conversion_For_File_X_Was_Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es ist ein Fehler beim Konvertieren aufgetreten: {0}.
        /// </summary>
        internal static string Program_HandleFile_Error_While_Converting_File_X {
            get {
                return ResourceManager.GetString("Program_HandleFile_Error_While_Converting_File_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versuche folgende Datei zu konvertieren: {0}.
        /// </summary>
        internal static string Program_HandleFile_Trying_To_Convert_File_X {
            get {
                return ResourceManager.GetString("Program_HandleFile_Trying_To_Convert_File_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es wurden {0} Dateien abgearbeitet..
        /// </summary>
        internal static string Program_Main_Converted_X_Files {
            get {
                return ResourceManager.GetString("Program_Main_Converted_X_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es wurden {0} erfolgreich konvertiert..
        /// </summary>
        internal static string Program_Main_Converted_X_Files_Successfully {
            get {
                return ResourceManager.GetString("Program_Main_Converted_X_Files_Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte geben Sie das Zieldateiformat an: .
        /// </summary>
        internal static string Program_Main_Enter_Destination_File_Path {
            get {
                return ResourceManager.GetString("Program_Main_Enter_Destination_File_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte geben Sie den Zielpfad an: .
        /// </summary>
        internal static string Program_Main_Enter_Destination_Path {
            get {
                return ResourceManager.GetString("Program_Main_Enter_Destination_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte geben Sie das Quelldateiformat an: .
        /// </summary>
        internal static string Program_Main_Enter_Source_File_Format {
            get {
                return ResourceManager.GetString("Program_Main_Enter_Source_File_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte geben Sie den Quellpfad an: .
        /// </summary>
        internal static string Program_Main_Enter_Source_Path {
            get {
                return ResourceManager.GetString("Program_Main_Enter_Source_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es ist ein Fehler beim Lesen der Dateien aufgetreten: {0}.
        /// </summary>
        internal static string Program_Main_Error_While_Reading_File_X {
            get {
                return ResourceManager.GetString("Program_Main_Error_While_Reading_File_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es wurden {0} Dateien für die Dateiendung &quot;{1}&quot; gefunden..
        /// </summary>
        internal static string Program_Main_Found_X_Files_For_X_File_Ending {
            get {
                return ResourceManager.GetString("Program_Main_Found_X_Files_For_X_File_Ending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keine Dateien gefunden!.
        /// </summary>
        internal static string Program_Main_No_Files_Found {
            get {
                return ResourceManager.GetString("Program_Main_No_Files_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Konvertierung dauerte {0}ms..
        /// </summary>
        internal static string Program_Main_The_Conversion_Took_X_Milliseconds {
            get {
                return ResourceManager.GetString("Program_Main_The_Conversion_Took_X_Milliseconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drücken Sie eine Taste um die Anwendung zu beenden....
        /// </summary>
        internal static string Program_Shutdown_Press_Any_Key_To_Exit {
            get {
                return ResourceManager.GetString("Program_Shutdown_Press_Any_Key_To_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Quellpfad ist ungültig..
        /// </summary>
        internal static string Program_ValidateInputFilePath_Invalid {
            get {
                return ResourceManager.GetString("Program_ValidateInputFilePath_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Quelldateiformat ist ungültig..
        /// </summary>
        internal static string Program_ValidateSourceFileEnding_Invalid {
            get {
                return ResourceManager.GetString("Program_ValidateSourceFileEnding_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Zielpfad ist ungültig..
        /// </summary>
        internal static string Program_ValidateTagetFilePath_Invalid {
            get {
                return ResourceManager.GetString("Program_ValidateTagetFilePath_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Zieldateiformat ist ungültig..
        /// </summary>
        internal static string Program_ValidateTargetFileEnding_Invalid {
            get {
                return ResourceManager.GetString("Program_ValidateTargetFileEnding_Invalid", resourceCulture);
            }
        }
    }
}
